name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
